import {Dimensions} from 'react-native';

export const ASCIITable = [
  {value: 0, data: '@'},
  {value: 1, data: 'A'},
  {value: 2, data: 'B'},
  {value: 3, data: 'C'},
  {value: 4, data: 'D'},
  {value: 5, data: 'E'},
  {value: 6, data: 'F'},
  {value: 7, data: 'G'},
  {value: 8, data: 'H'},
  {value: 9, data: 'I'},
  {value: 10, data: 'J'},
  {value: 11, data: 'K'},
  {value: 12, data: 'L'},
  {value: 13, data: 'M'},
  {value: 14, data: 'N'},
  {value: 15, data: 'O'},
  {value: 16, data: 'P'},
  {value: 17, data: 'Q'},
  {value: 18, data: 'R'},
  {value: 19, data: 'S'},
  {value: 20, data: 'T'},
  {value: 21, data: 'U'},
  {value: 22, data: 'V'},
  {value: 23, data: 'W'},
  {value: 24, data: 'X'},
  {value: 25, data: 'Y'},
  {value: 26, data: 'Z'},
  {value: 27, data: '['},
  {value: 28, data: '\\'},
  {value: 29, data: ']'},
  {value: 30, data: '^'},
  {value: 31, data: '_'},
  {value: 32, data: '\xa0'},
  {value: 33, data: '!'},
  {value: 34, data: '"'},
  {value: 35, data: '#'},
  {value: 36, data: '$'},
  {value: 37, data: '%'},
  {value: 38, data: '&'},
  {value: 39, data: "'"},
  {value: 40, data: '('},
  {value: 41, data: ')'},
  {value: 42, data: '*'},
  {value: 43, data: '+'},
  {value: 44, data: ','},
  {value: 45, data: '-'},
  {value: 46, data: '.'},
  {value: 47, data: '/'},
  {value: 48, data: '0'},
  {value: 49, data: '1'},
  {value: 50, data: '2'},
];

export const windowWidth = Dimensions.get('window').width;
export const windowHeight = Dimensions.get('window').height;
